// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package accounts

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    public_id, 
    email, 
    password_hash
) VALUES (
    $1, $2, $3
)
RETURNING id
`

type CreateAccountParams struct {
	PublicID     pgtype.UUID
	Email        string
	PasswordHash string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (int32, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.PublicID, arg.Email, arg.PasswordHash)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getAccountWithEmail = `-- name: GetAccountWithEmail :one
SELECT id, public_id, email, password_hash, created_at, updated_at FROM accounts WHERE email = $1
`

func (q *Queries) GetAccountWithEmail(ctx context.Context, email string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountWithEmail, email)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountWithID = `-- name: GetAccountWithID :one
SELECT id, public_id, email, password_hash, created_at, updated_at FROM accounts WHERE public_id = $1
`

func (q *Queries) GetAccountWithID(ctx context.Context, publicID pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountWithID, publicID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccountEmailWithID = `-- name: UpdateAccountEmailWithID :exec
UPDATE accounts
    SET email = $1
WHERE public_id = $2
`

type UpdateAccountEmailWithIDParams struct {
	Email    string
	PublicID pgtype.UUID
}

func (q *Queries) UpdateAccountEmailWithID(ctx context.Context, arg UpdateAccountEmailWithIDParams) error {
	_, err := q.db.Exec(ctx, updateAccountEmailWithID, arg.Email, arg.PublicID)
	return err
}

const updatePasswordWithID = `-- name: UpdatePasswordWithID :exec
UPDATE accounts
    SET password_hash = $1
WHERE public_id = $2
`

type UpdatePasswordWithIDParams struct {
	PasswordHash string
	PublicID     pgtype.UUID
}

func (q *Queries) UpdatePasswordWithID(ctx context.Context, arg UpdatePasswordWithIDParams) error {
	_, err := q.db.Exec(ctx, updatePasswordWithID, arg.PasswordHash, arg.PublicID)
	return err
}
