// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package accounts

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID           int32
	PublicID     pgtype.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}
