@baseUrl = http://localhost:8080
@token = mytoken

### CREATE USER
POST {{baseUrl}}/api/v1/users
content-type: application/json

{
    "firstName": "Sahil",
    "lastName": "Rane",
    "email": "noreply@ecommerce.comx",
    "phone": "7217217217",
    "password": "test@123",
    "confirmPassword": "test@123"
}

### GET USER
GET {{baseUrl}}/api/v1/users/1

### UPDATE USER
PUT {{baseUrl}}/api/v1/users/1
content-type: application/json

{
    "firstName": "Sahil",
    "lastName": "Rane",
    "email": "noreply@ecommerce.comx",
    "phone": "7217217217",
    "password": "test@123",
    "confirmPassword": "test@123"
}

### DELETE USER
DELETE {{baseUrl}}/api/v1/users/3
