root = "."

tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ."
  bin = "./tmp/main"
  include_ext = ["go", "yaml", "yml", "json"]
  exclude_dir = ["tmp", "bin", "vendor", ".git"]
  delay = 500
  stop_on_error = true

[log]
  time = true

[misc]
  clean_on_exit = true
