run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 10
  tests: false
  allow-parallel-runners: true
  allow-serial-runners: true
  go: "1.22"
output:
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  show-stats: false
  sort-results: true
  formats:
    - format: json
      path: golangci-lint-report.txt
    - format: colored-line-number
      path: stdout
linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - exportloopref
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagalign
    - tagliatelle
    - tenv
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
    - zerologlint
linters-settings:
  gofumpt:
    extra-rules: true
  revive:
    severity: error
    rules:
      - name: add-constant
      - name: atomic
      - name: argument-limit
        arguments: [4]
      - name: banned-characters
      - name: call-to-gc
      - name: cognitive-complexity
        arguments: [15]
      - name: confusing-naming
      - name: confusing-results
      - name: constant-logical-expr
      - name: context-as-argument
      - name: context-keys-type
      - name: cyclomatic
        arguments: [10]
      - name: datarace
      - name: deep-exit
      - name: defer
      - name: dot-imports
      - name: duplicated-imports
      - name: early-return
      - name: empty-block
      - name: empty-lines
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: errorf
      - name: exported
      - name: flag-parameter
      - name: function-result-limit
        arguments: [3]
      - name: function-length
        arguments: [25,0]
      - name: get-return
      - name: identical-branches
      - name: if-return
      - name: import-alias-naming
      - name: import-shadowing
      - name: imports-blocklist
      - name: increment-decrement
      - name: indent-error-flow
      - name: line-length-limit
        arguments: [120]
      - name: max-control-nesting
        arguments: [3]
      - name: modifies-parameter
      - name: modifies-value-receiver
      - name: optimize-operands-order
      - name: range-val-address
      - name: range-val-in-closure
      - name: range
      - name: receiver-naming
      - name: redefines-builtin-id
      - name: redundant-import-alias
      - name: string-of-int
      - name: struct-tag
      - name: superfluous-else
      - name: time-equal
      - name: time-naming
      - name: unchecked-type-assertion
      - name: unconditional-recursion
      - name: unexported-naming
      - name: unhandled-error
      - name: unnecessary-stmt
      - name: unreachable-code
      - name: unused-parameter
      - name: unused-receiver
        arguments: [ { allowRegex = "^_" } ]
      - name: use-any
      - name: useless-break
      - name: var-declaration
      - name: var-naming
      - name: waitgroup-by-value
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/ranefattesingh/microservices/user)
      - prefix(github.com/ranefattesingh/microservices)
      - prefix(github.com/ranefattesingh/pkg)
  unparam:
    check-exported: true
  tagliatelle:
    case:
      rules:
        json: snake
        yaml: snake
severity:
  default-severity: error
  
  